name: CI Pipeline

# Testing runs on *any* push to the repo and can also be triggered manually.
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.15.0'

    - name: Install dependencies
      run: npm install

    # - name: Run lint
    #   run: npm run lint

    - name: Run tests
      run: npm test

    - name: Run e2e tests
      run: npm run test:e2e

    # - name: Run formatter
    #   run: npm run format

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
        ECR_REPOSITORY: my-nestjs-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Deploy to ECS
      env:
        AWS_REGION: us-east-1
        ECS_SERVICE: my-ecs-service
        ECS_CLUSTER: my-ecs-cluster
        IMAGE_URI: ${{ steps.ecr-login.outputs.registry }}/my-nestjs-app:${{ github.sha }}
      run: |
        aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment --region $AWS_REGION
